### PR TITLE
REBASE: ATTEMPT 2

### PR DESCRIPTION
**Pull request by Nekoyre**
I FINALLY FIGURED OUT GITHUB NOW MERGE IT PELASE

### CODE REVIEW

**Comment by Nekoyre** [comment]
i also made a command called `didyourolla69`, anyways time for bed, its 1:30am

**Comment by Nekoyre** [comment]
and i fixed your deps*

**Comment by Nekoyre** [comment]
and constructors

**Comment by Nekoyre** [comment]
mk thx gn

**Review by TogarashiPepper — COMMENTED** [review]
Hey Neko, could you undo the changes you made to the buttons on src/commands/eval.ts, these values being stored at the top is intentional, I intend to move it to a file in src/util so it's fine if you don't undo the changes.

**Pull request merged**
